[package]
name = "blankwindow-gtk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug_print = "1.0.0"
dirs = "5.0.0"
glib = "0.17.9"
gtk = "0.17.1"
